MIS4200Group6/Controllers/GamificationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MIS4200Group6.DAL;
using MIS4200Group6.Models;

namespace MIS4200Group6.Controllers
{
    public class GamificationsController : Controller
    {
        private CentricContext db = new CentricContext();

        // GET: Gamifications
        public ActionResult Index()
        {
            var gamification = db.Gamifications.Include(g => g.GiveRecogniton);
            return View(gamification.ToList());
           // return View(db.Gamifications.ToList());
        }

        // GET: Gamifications/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gamification gamification = db.Gamifications.Find(id);
            if (gamification == null)
            {
                return HttpNotFound();
            }
            return View(gamification);
        }

        // GET: Gamifications/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Gamifications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,gamificationId")] Gamification gamification)
        {
            if (ModelState.IsValid)
            {
                gamification.ID = Guid.NewGuid();
                db.Gamifications.Add(gamification);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gamification);
        }

        // GET: Gamifications/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gamification gamification = db.Gamifications.Find(id);
            if (gamification == null)
            {
                return HttpNotFound();
            }
            return View(gamification);
        }

        // POST: Gamifications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,gamificationId")] Gamification gamification)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gamification).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gamification);
        }

        // GET: Gamifications/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Gamification gamification = db.Gamifications.Find(id);
            if (gamification == null)
            {
                return HttpNotFound();
            }
            return View(gamification);
        }

        // POST: Gamifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Gamification gamification = db.Gamifications.Find(id);
            db.Gamifications.Remove(gamification);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MIS4200Group6/Controllers/GiveRecognitionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MIS4200Group6.DAL;
using MIS4200Group6.Models;
using System.Net;
using System.Net.Mail;
using Microsoft.AspNet.Identity;

namespace MIS4200Group6.Controllers
{
    public class GiveRecognitionsController : Controller
    {
        private CentricContext db = new CentricContext();

        // GET: GiveRecognitions
        public ActionResult Index(Guid? ID, string emp)
        {
            var giveRecognitions = db.GiveRecognitions.Include(g => g.UserDetails).Include(g => g.UserDetails);

            if (ID != null)
            {
                giveRecognitions = db.GiveRecognitions.Where(g => g.ID == ID).Include(g => g.ID).Include(g => g.values).Include(g => g.EmployeeGivingRecog);
                ViewBag.Awardee = emp;
                var awards = (from aw in giveRecognitions
                              group aw by new
                              { g = aw.UserDetails.ID, a = aw.values } into e
                              select new
                              { receiverID = e.Key.g, awardID = e.Key.a, AwardCount = e.Count() });
                ViewBag.AwardList = awards.ToList();

                return View("Awards");
            }
            else
            {
                return View(giveRecognitions.ToList());
            }
        }

        // GET: GiveRecognitions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiveRecognition giveRecognition = db.GiveRecognitions.Find(id);
            if (giveRecognition == null)
            {
                return HttpNotFound();
            }
            return View(giveRecognition);
        }

        // GET: GiveRecognitions/Create
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.EmployeeGivingRecog = new SelectList(db.UserDetails, "ID", "fullName");
                ViewBag.ID = new SelectList(db.UserDetails, "ID", "fullName");
                return View();
            }
            else
            {
                return View("NotAuthenticated2");
            }
            
        }

        // POST: GiveRecognitions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeeRecognitionID,values,CurentDateTime,RecognitionComments,EmployeeGivingRecog,ID")] GiveRecognition giveRecognition)
        {
            if (ModelState.IsValid)
            {
                Guid memberId;
                Guid.TryParse(User.Identity.GetUserId(), out memberId);
                giveRecognition.EmployeeGivingRecog = memberId;
                db.GiveRecognitions.Add(giveRecognition);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeGivingRecog = new SelectList(db.UserDetails, "ID", "email", giveRecognition.EmployeeGivingRecog);
            ViewBag.ID = new SelectList(db.UserDetails, "ID", "email", giveRecognition.ID);
            return View(giveRecognition);
        }

        // GET: GiveRecognitions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiveRecognition giveRecognition = db.GiveRecognitions.Find(id);
            if (giveRecognition == null)
            {
                return HttpNotFound();
            }
            Guid memberID;
            Guid.TryParse(User.Identity.GetUserId(), out memberID);
            if (giveRecognition.EmployeeGivingRecog == memberID)
            {
                ViewBag.EmployeeGivingRecog = new SelectList(db.UserDetails, "ID", "fullName", giveRecognition.EmployeeGivingRecog);
                ViewBag.ID = new SelectList(db.UserDetails, "ID", "fullName", giveRecognition.ID);
                return View(giveRecognition);
            }
            else
            {
                return View("NotAuthenticated2");
            }

          
        }

        // POST: GiveRecognitions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeRecognitionID, values, CurentDateTime,RecognitionComments,EmployeeGivingRecog,ID")] GiveRecognition giveRecognition)
        {
            if (ModelState.IsValid)
            {
                db.Entry(giveRecognition).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeGivingRecog = new SelectList(db.UserDetails, "ID", "email", giveRecognition.EmployeeGivingRecog);
            ViewBag.ID = new SelectList(db.UserDetails, "ID", "email", giveRecognition.ID);
            return View(giveRecognition);
        }

        // GET: GiveRecognitions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiveRecognition giveRecognition = db.GiveRecognitions.Find(id);
            if (giveRecognition == null)
            {
                return HttpNotFound();
            }
            Guid memberID;
            Guid.TryParse(User.Identity.GetUserId(), out memberID);
            if (giveRecognition.EmployeeGivingRecog == memberID)
            {
                return View(giveRecognition);
            }
            else
            {
                return View("NotAuthenticated2");
            }
        }

        // POST: GiveRecognitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GiveRecognition giveRecognition = db.GiveRecognitions.Find(id);
            db.GiveRecognitions.Remove(giveRecognition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MIS4200Group6/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MIS4200Group6.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MIS4200Group6/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Main Contacts";
}
<h2>@ViewBag.Title.</h2>
<br />
<br/>

<div class="row">
    <div class="col-md-3">
        <h4>Gina Heffner</h4>
        <p><img src="~/Content/Images/img_gina.jpg" /></p>
        <p>Columbus, Director<br />
        Active<br/>
        <abbr title="Phone">P: </abbr>740.485.2910<br/>
        <abbr title="Email">E: </abbr><a href="mailto:gina.heffner@centricconsulting.com">gina.heffner@centricconsulting.com</a></p>
    </div>
    <div class="col-md-3">
        <h4>Brad Stagmyer</h4>
        <p><img src="~/Content/Images/img_brad.jpg" /></p>
        Columbus, Director<br/>
        Active<br/>
        <abbr title="Phone">P: </abbr>614.205.8112<br/>
        <abbr title="Email">E: </abbr><a href="mailto:brad.stagmyer@centricconsulting.com">brad.stagmyer@centricconsulting.com</a></p>
    </div>
    </div>

<div class="row">
    <div class="col-md-3">
        <h4>Gwenn Denorme</h4>
        <p><img src="~/Content/Images/img_gwenn.jpg" /></p>
        Columbus, Director<br/>
        Active<br/>
        <abbr title="Phone">P: </abbr>614.205.1384<br/>
        <abbr title="Email">E: </abbr><a href="mailto:gwenn.denorme@centricconsulting.com">gwenn.denorme@centricconsulting.com</a></p>
    </div>
    <div class="col-md-3">
        <h4>Doug Hood</h4>
        <p><img src="~/Content/Images/img_doug.jpg" /></p>
        Columbus, Director<br/>
        Active<br/>
        <abbr title="Phone">P: </abbr>614.599.3963<br/>
        <abbr title="Email">E: </abbr><a href="mailto:doug.hood@centricconsulting.com">doug.hood@centricconsulting.com</a></p>
    </div>
</div>

MIS4200Group6/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <img src="http://www.worldoftalentmanagement.com/Media/Default/images/Centric_in_balance_web.jpg" alt="Hi" width="250">
    <h1>Employee Recognition Platform</h1>
    <p class="lead">Here at Centric we care about our employees. We want to create a culture where employees are accepted, challenged, and recognized for their hard work that gets unnoticed by other employees in the firm.</p>
    <p><a href="http://cob.ohio.edu/mis4200Team6/Home/About" class="btn btn-success">Learn more about this application &raquo;</a></p>
</div>



<div class="row">
    <div class="col-md-4">


        @*<p align="center"><a class="btn btn-default" href="https://twitter.com/centric?ref_src=twsrc%5Etfw"> Centric Twitter Page</a></p>*@

        @*<h2 align="center"><a href="https://twitter.com/centric?ref_src=twsrc%5Etfw"> Centric Twitter Page</a></h2>*@

        <h1 align="center" @*style="border:solid"*@>

            <a class="twitter-timeline" width="650" height="250" href="https://twitter.com/centric?ref_src=twsrc%5Etfw">Tweets by centric</a>

            <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

        </h1>

        @*<p>Want to learn more about how we stick to our Core Values? Visit our website to find more information about our employees and how to incorporate the Core Values into your every day life!</p>*@

        @*<p><a class="btn btn-default" href="https://centricconsulting.com/about-us/">Learn more &raquo;</a></p>*@

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- Add font awesome icons -->
        @*<a href="#" class="fa fa-facebook" ></a>*@



      
        
       
    </div>
    <div class="col-md-4">
        <h2>Core Values</h2>
        <p>Our core values reflect our professional passions and personal convictions.</p>
        <p> @Html.ActionLink("Our Core Values", "About", "Home", null, new { @class = "btn btn-primary btn-large" })</p>
    </div>
    <div class="col-md-4">
        <h2>Recognize</h2>
        <p>Recognize your colleagues on noticable hardwork and achievements </p>
       
        <p> @Html.ActionLink("Give Recognition", "Index", "GiveRecognitions", null, new { @class = "btn btn-primary btn-large" })</p>
        <p> @Html.ActionLink("Recognition", "Index", "Gamifications", null, new { @class = "btn btn-primary btn-large" })</p>
    </div>
</div>