MIS4200Group6/Controllers/MyRecognitionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MIS4200Group6.DAL;
using MIS4200Group6.Models;
using Microsoft.AspNet.Identity;

namespace MIS4200Group6.Controllers
{
    public class MyRecognitionsController : Controller
    {
        private CentricContext db = new CentricContext();

        // GET: MyRecognitions
        public ActionResult Index()
        {
            Guid userID;
            Guid.TryParse(User.Identity.GetUserId(), out userID);

            var giveRecognitions = db.GiveRecognitions.Where(g => g.ID == userID).OrderByDescending(g => g.CurentDateTime);
            var totalRecogs = (from s in giveRecognitions
                            select s.ID).Count();
            return View(giveRecognitions.ToList());
        }

        // GET: MyRecognitions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiveRecognition giveRecognition = db.GiveRecognitions.Find(id);
            if (giveRecognition == null)
            {
                return HttpNotFound();
            }
            return View(giveRecognition);
        }

        // GET: MyRecognitions/Create
        public ActionResult Create()
        {
            /*ViewBag.EmployeeGivingRecog = new SelectList(db.UserDetails, "ID", "email");
            ViewBag.ID = new SelectList(db.UserDetails, "ID", "email");*/
            return View();
        }

        // POST: MyRecognitions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeeRecognitionID,CurentDateTime,values,RecognitionComments,EmployeeGivingRecog,ID")] GiveRecognition giveRecognition)
        {
            if (ModelState.IsValid)
            {
                db.GiveRecognitions.Add(giveRecognition);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

           /*ViewBag.EmployeeGivingRecog = new SelectList(db.UserDetails, "ID", "email", giveRecognition.EmployeeGivingRecog);
            ViewBag.ID = new SelectList(db.UserDetails, "ID", "email", giveRecognition.ID);*/
            return View(giveRecognition);
        }

        // GET: MyRecognitions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiveRecognition giveRecognition = db.GiveRecognitions.Find(id);
            if (giveRecognition == null)
            {
                return HttpNotFound();
            }
           /* ViewBag.EmployeeGivingRecog = new SelectList(db.UserDetails, "ID", "email", giveRecognition.EmployeeGivingRecog);
            ViewBag.ID = new SelectList(db.UserDetails, "ID", "email", giveRecognition.ID);*/
            return View(giveRecognition);
        }

        // POST: MyRecognitions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeRecognitionID,CurentDateTime,values,RecognitionComments,EmployeeGivingRecog,ID")] GiveRecognition giveRecognition)
        {
            if (ModelState.IsValid)
            {
                db.Entry(giveRecognition).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EmployeeGivingRecog = new SelectList(db.UserDetails, "ID", "email", giveRecognition.EmployeeGivingRecog);
            ViewBag.ID = new SelectList(db.UserDetails, "ID", "email", giveRecognition.ID);
            return View(giveRecognition);
        }

        // GET: MyRecognitions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GiveRecognition giveRecognition = db.GiveRecognitions.Find(id);
            if (giveRecognition == null)
            {
                return HttpNotFound();
            }
            return View(giveRecognition);
        }

        // POST: MyRecognitions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GiveRecognition giveRecognition = db.GiveRecognitions.Find(id);
            db.GiveRecognitions.Remove(giveRecognition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MIS4200Group6/Controllers/userDetailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using MIS4200Group6.DAL;
using MIS4200Group6.Models;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;
using System.IO;
using System.Drawing;

namespace MIS4200Group6.Controllers
{
    public class userDetailsController : Controller
    {
        private CentricContext db = new CentricContext();

        // GET: userDetails

        public ActionResult Index(string searchString)
        {
            var testuserdetails = from u in db.UserDetails select u;
            if (!String.IsNullOrEmpty(searchString))
            {
                testuserdetails = testuserdetails.Where(u => u.lastName.Contains(searchString) || u.firstName.Contains(searchString));
                return View(testuserdetails.ToList());
            }
            return View(db.UserDetails.ToList());
        }

        // GET: userDetails/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            userDetails userDetails = db.UserDetails.Find(id);
            if (userDetails == null)
            {
                return HttpNotFound();
            }
            return View(userDetails);
        }

        // GET: userDetails/Create

        [HttpGet]
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.email = User.Identity.Name;
                return View();
            }
            else
            {
                return View("NotAuthenticated2");
            }
            
        }

        // POST: userDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,email,firstName,lastName,phoneNumber,office,Position,HireDate,numberOfYears,photo")] userDetails userDetails)
        {

           
            if (ModelState.IsValid)
            {
                
                HttpPostedFileBase file = Request.Files["photo"];
                
                if (file != null && file.FileName != null && file.FileName != "")
                {
                    FileInfo fi = new FileInfo(file.FileName);
                    if (fi.Extension !=".jpeg" && fi.Extension !=".jpg" && fi.Extension !="gif")
                    {
                        TempData["Errormsg"] = "Image File Extension is not valid";
                        return View(userDetails);
                    }
                    else
                    {
                        userDetails.photo = userDetails.ID + fi.Extension;
                        file.SaveAs(Server.MapPath("~/Content/Images/" + userDetails.ID + fi.Extension));

                    }
                }

                Guid memberId;
                Guid.TryParse(User.Identity.GetUserId(), out memberId);
                userDetails.ID = memberId;
                userDetails.email = User.Identity.Name;
                //userDetails.ID = Guid.NewGuid();
                db.UserDetails.Add(userDetails); 
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(userDetails);
        }

        // GET: userDetails/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            userDetails userDetails = db.UserDetails.Find(id);
            if (userDetails == null)
            {
                return HttpNotFound();
            }
            Guid memberID;
            Guid.TryParse(User.Identity.GetUserId(), out memberID);
            if (userDetails.ID == memberID)
            {
                return View(userDetails);
            }
            else
            {
                return View("NotAuthenticated2");
            }

        }

        // POST: userDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,email,firstName,lastName,phoneNumber,office,Position,HireDate,numberOfYears,photo")] userDetails userDetails)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userDetails).State = EntityState.Modified;
                HttpPostedFileBase file = Request.Files["photo"];
                if (file !=null && file.FileName !=null && file.FileName !="")
                {
                    FileInfo fi = new FileInfo(file.FileName);
                    if (fi.Extension !=".jpeg" && fi.Extension !=".jpg" && fi.Extension !="gif")
                    {
                        TempData["Errormsg"] = "Image File Extension is not valid";
                        return View(userDetails);
                    }
                    else
                    {
                        userDetails imageOld = db.UserDetails.Find(userDetails.ID);
                        string imageName = imageOld.photo;
                        string path = Server.MapPath("~/Content/Images/" + imageName);
                    try
                        {
                            if (System.IO.File.Exists(path))
                            {
                                System.IO.File.Delete(path);
                            }
                            else
                            {

                            }
                        }
                        catch (Exception Ex)
                        {

                        }
                        userDetails.photo = userDetails.ID + fi.Extension;
                        file.SaveAs(Server.MapPath("~/Content/Images/" + userDetails.ID + fi.Extension));
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userDetails);
        }

        // GET: userDetails/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            userDetails userDetails = db.UserDetails.Find(id);
            if (userDetails == null)
            {
                return HttpNotFound();
            }
            Guid memberID;
            Guid.TryParse(User.Identity.GetUserId(), out memberID);
            if (userDetails.ID == memberID)
            {
                return View(userDetails);
            }
            else
            {
                return View("NotAuthenticated2");
            }
            //return View(userDetails);
        }

        // POST: userDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            userDetails userDetails = db.UserDetails.Find(id);
            string imageName = userDetails.photo;
            string path = Server.MapPath("~/Content/Images/" + imageName);
            try
            {
                System.IO.File.Delete(path);
            }
            catch (Exception Ex)
            {

            }
            db.UserDetails.Remove(userDetails);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MIS4200Group6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Centric Consulting</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Centric Consulting", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Recognize an Employee","Index","GiveRecognitions")</li>
                    <li>@Html.ActionLink("Employee Info", "Index", "userDetails")</li>
                    <li>@Html.ActionLink("Your Recognitions", "Index", "MyRecognitions")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MIS4200Team6
            <html>
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1">
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
                <style>
                    .fa {
                        padding: 10px;
                        font-size: 25px;
                        width: 50px;
                        text-align: center;
                        text-decoration: none;
                        margin: 3px 1px;
                        border-radius: 40%;
                    }

                        .fa:hover {
                            opacity: 0.7;
                        }

                    .fa-facebook {
                        background: #3B5998;
                        color: white;
                    }

                    .fa-twitter {
                        background: #55ACEE;
                        color: white;
                    }

                    .fa-linkedin {
                        background: #007bb5;
                        color: white;
                        align-content: flex-start;
                    }
                </style>
            </head>
<body>
    <a href="https://www.facebook.com/CentricConsultingNational/" class="fa fa-facebook"></a>
    <a href="https://twitter.com/centric?ref_src=twsrc%5Etfw" class="fa fa-twitter"></a>
    <a href="https://www.linkedin.com/company/centric-consulting" class="fa fa-linkedin"></a>

</body>

                
</html>
    </footer>

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>